# Contract: GitHub Actions CI Workflow Schema
# Location: .github/workflows/ci.yml
# Purpose: Defines required structure for CI/CD validation

# REQUIRED: Workflow name
name: CI

# REQUIRED: Trigger configuration
on:
  pull_request:  # REQUIRED: Run on PR
    branches:
      - main  # REQUIRED: At minimum, run on main branch PRs
  push:
    branches:
      - main  # REQUIRED: Run on pushes to main

# REQUIRED: Jobs configuration
jobs:
  lint-and-test:  # Job name (can be customized)
    runs-on: ubuntu-latest  # REQUIRED: Use ubuntu runner

    steps:
      # REQUIRED: Checkout code
      - uses: actions/checkout@v4

      # REQUIRED: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # REQUIRED: Must match Ruff target-version

      # REQUIRED: Install dependencies
      - name: Install dependencies
        run: |
          pip install ruff pytest  # REQUIRED: Install Ruff and pytest
          pip install -e .  # REQUIRED: Install project

      # REQUIRED: Ruff format check (must match pre-commit)
      - name: Ruff format check
        run: ruff format --check .

      # REQUIRED: Ruff lint check (must match pre-commit)
      - name: Ruff lint check
        run: ruff check .

      # REQUIRED: Run tests
      - name: Run tests
        run: pytest

# Contract Test: test_github_actions.py
# Validates:
# 1. .github/workflows/ci.yml exists
# 2. Workflow triggers on pull_request and push events
# 3. Jobs run on ubuntu-latest
# 4. Python version is 3.11 or higher
# 5. Ruff is installed
# 6. pytest is installed
# 7. Ruff format check runs
# 8. Ruff lint check runs
# 9. pytest runs
# 10. All required steps are present in correct order
